- name: start container
  community.docker.docker_container:
    name: glance
    image: glanceapp/glance
    recreate: true
    restart: true
    ports:
      - '2002:8080'
    env:
      WEBSERVER_API_PASSWORD: '{{ webserver_api_password }}'
      AGENT_TOKEN: '{{ agent_token }}'
    volumes:
      - '{{ playbook_dir }}/roles/glance/files/config:/app/config'
      - '{{ playbook_dir }}/roles/glance/files/assets:/app/assets'
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - name: '{{ network }}'
    state: started
