- name: setup services server
  hosts: localhost
  connection: local
  vars_files:
    - vars/all.yml
    - vars/vault.yml
  become: true

  roles:
    - network
    - docker
    - caddy
    - pihole
    - glance
    - navidrome
    - qbittorrent
