- name: start container
  community.docker.docker_container:
    name: caddy
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    recreate: true
    restart: true
    ports:
      - '2000:80'
      - '443:443'
      - '443:443/udp'
    env:
      CLOUDFLARE_API_TOKEN: '{{ cloudflare_api_token }}'
    volumes:
      - '{{ playbook_dir }}/roles/caddy/files/Caddyfile:/etc/caddy/Caddyfile:ro'
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - name: '{{ network }}'
    state: started
