- name: start container
  community.docker.docker_container:
    name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    recreate: true
    restart: true
    ports:
      - '2004:2004'
      - '6881:6881'
      - '6881:6881/udp'
    env:
      PUID: '1000'
      GUID: '1000'
      WEBUI_PORT: '2004'
      TORRENTING_PORT: '6881'
    volumes:
      - '/opt/qbittorrent/config:/config'
      - '/opt/navidrome/music:/downloads'
    networks:
      - name: '{{ network }}'
    state: started
